### ISSUE TITLE
Jest version 19 docset

### ISSUE THREAD

**Issue by gingermusketeer** [epitaphmike/jest-dash#1]
https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Jest suggested that an issue be created here to get the latest version jest docs added to the user contrib repo.

Is it just a case of running the build script and creating a PR to the user contrib repo?

**Comment by epitaphmike** [comment]
Unfortunately not. The docs setup has changed a bit. I will look at an update, especially since the new v.19 docs are a lot different. I also need to update React Native, Flow and Draft.

**Comment by epitaphmike** [comment]
I updated the code in the script-runner repo and also submitted the new docset to Dash. It should be available shortly when the PR is merged.

**Comment by gingermusketeer** [comment]
@epitaphmike WOW. Thanks so much for doing that :) :)

**Comment by epitaphmike** [comment]
You bet. It's been on my TODO list for a while. I've just been dragging my feet.
